[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/nfimap-plus/*"
  to = "https://nfimap-plus.netlify.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
